version: 2
updates:
    # Enable version updates for npm
    - package-ecosystem: "npm"
      # Look for `package.json` and `package-lock.json` in the `root` directory
      directory: "/"
      # Check the npm registry for updates every day (weekdays)
      schedule:
          interval: "daily"
      # Allow up to 10 open PRs
      open-pull-requests-limit: 10
      # Keep existing labels on pull requests
      labels:
          - "dependencies"
      # Assign the following reviewers to pull requests
      reviewers:
          - "dependabot"
          - "dependabot[bot]"
          - "maurrod2001"
      commit-message:
          prefix: "[npm] "
      commit-message:
          prefix: "[npm] "
    # Enable version updates for npm
    - package-ecosystem: "npm"
      # Look for `package.json` and `package-lock.json` in the `root` directory
      directory: "/"
      # Check the npm registry for updates every day (weekdays)
      schedule:
          interval: "daily"
      target-branch: "js-source-final"
      # Allow up to 10 open PRs
      open-pull-requests-limit: 10
      # Keep existing labels on pull requests
      labels:
          - "dependencies"
      # Assign the following reviewers to pull requests
      reviewers:
          - "dependabot"
          - "dependabot[bot]"
          - "maurrod2001"
      commit-message:
          prefix: "[npm on dev] "